//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S00212883_Year2_Semester2_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubFactions()
        {
            this.Units = new HashSet<Units>();
        }
    
        public int SubFactionID { get; set; }
        public string Name { get; set; }
        public int FactionID { get; set; }
    
        public virtual Factions Faction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Units> Units { get; set; }
    }
}
